spring:
  application:
    name: ms-contato
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: test

server:
  port: 8181
  servlet:
    context-path: /api
  